---
title: "Support Vector Machines"
author: "Patrick Barajas"
date: "9/18/2017"
output: html_document
---
# Support Vector Machines with R practice

```{r}
library(ISLR)
```

```{r}
head(iris, 5)
```
```{r}
## to use VMMs we need to install the e1071 packacge that has the packages
library(e1071)
## help("svm") for the documentation
```

```{r}
model <- svm(Species ~., data = iris)
summary(model)
```

```{r}
## If we wanted to predict number we would pass in our training data
pred.values <- predict (model, iris[1:4])
table(pred.values,iris[,5])
```
cost is what allows the NVM to have a 'soft' margin; the svm allows some 
samples to be added to the wrong side of the classification margin.

* gamma large = variance small

* large gamma = high bias

## Tuning Parameters
```{r}
tune.results <- tune(svm, train.x =  - iris[1:4], train.y = iris[,5], kernal = 'radial',
                     ranges = list(cost = c(0.1,1,10), gamma = c(0.5, 1, 2)))
```

```{r}
summary(tune.results)
```
We can look at the above results, then start to choose gamma values above and below the best parameters.
