---
title: "KNN with R"
author: "Patrick Barajas"
date: "9/17/2017"
output: html_document
---

# KNN with R
```{R}
library(ISLR)
str(Caravan)
```
This is a bunch of customer data across 85 predictors with the $Purchase column
indicating whether they made a purchase or not. Note only about 5% bought the insureance

```{r}
summary(Caravan$Purchase)
```
checking for na values
```{r}
any(is.na(Caravan))
```
```{r}
purchase <- Caravan[,86]
```
## Standardizing Variables
```{r}
standardize.Caravan <- scale(Caravan[,-86])
```

```{r}
print(var(standardize.Caravan[,1]))
print(var(standardize.Caravan[,2]))
```
## Train Test Split
```{r}
## We could use CATools to randomly split the test data.
## but instead we will just grab the first 1000 rows.
test.index <- 1:1000
test.data <- standardize.Caravan[test.index,]
test.purchase <- purchase[test.index]

## Train
train.data <- standardize.Caravan[-test.index,]
train.purchase <- purchase[-test.index]
```

# KNN Model
```{r}
library(class)
set.seed(101)
```

```{r}
predicted.purchase <- knn(train.data, test.data, train.purchase, k = 1)
print(head(predicted.purchase))
```
## Model Evaluation
```{r}
misclass.error <- mean(test.purchase != predicted.purchase)
print(misclass.error)
```
## Choosing a K Value
```{r}
predicted.purchase <- NULL
error.rate <- NULL
```

```{r}
for (i in 1:20){
        set.seed(101)
        predicted.purchase <- knn(train.data, test.data, train.purchase, k = i)
        error.rate[i] <- mean(test.purchase != predicted.purchase)
}
```

## Visualize K Elbow Method
```{r}
library(ggplot2)
k.values <- 1:20
error.df <- data.frame(error.rate, k.values)
```

```{r}
print(error.df)
```

```{r}
ggplot(error.df, aes(k.values, error.rate)) + geom_point() +
        geom_line(lty = "dotted", color = "red")
```

